language: scala
jdk:
  - oraclejdk8
script:
  - sbt compile
  # Ensure that scalariform was clean
  - git --no-pager diff --exit-code
  - sbt test
# Cache dependencies
cache:
 directories:
 - $HOME/.sbt
 - $HOME/.ivy2